services:
  - type: web
    name: telegram-anime-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_real_token_here
    build:
      environment:
        pythonVersion: 3.11.9
